name: flutter_auth
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.14.0+2
  flutter:
    sdk: flutter
  firebase_core : ^0.5.0
  flutter_launcher_icons: ^0.8.0
  timewheel: ^0.0.2

  http: ^0.12.2

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  line_awesome_flutter: ^1.0.1
  intl: ^0.16.1
  rflutter_alert: ^1.1.0
  qr_flutter: ^3.2.0
  flutter_typeahead: ^1.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_cupertino_date_picker:
    git: https://github.com/yasseralsamman/flutter-cupertino-date-picker.git

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay.ttf
